parameters:
  jaxon:
    app:
      directories:
        -
          path: '%kernel.project_dir%/ajax'
          namespace: Demo\Ajax
      dialogs:
        default:
          modal:                      bootbox
          alert:                      cute
      container:
        auto:
          - App\Service\Example
        alias:
          App\Service\ExampleInterface: App\Service\Example

    lib:
      core:
        language:                     "en"
        encoding:                     "UTF-8"
        request:
          uri:                        "/jaxon"
        prefix:
          class:                      ""
        debug:
          on:                         false
          verbose:                    false
        error:
          handle:                     false
      js:
        lib:
        app:
        export:                       false
        minify:                       false
