parameters:
  jaxon:
    app:
      directories:
        '%kernel.project_dir%/jaxon/ajax':
          namespace: \Jaxon\Demo\Ajax
          register: false
          # separator: '' # '.' or '_'
          # protected: []
      container:
        auto:
          - App\Service\Example
        alias:
          App\Service\ExampleInterface: App\Service\Example

    lib:
      core:
        language:                     "en"
        encoding:                     "UTF-8"
        request:
          uri:                        "/jaxon"
        prefix:
          class:                      ""
        debug:
          on:                         false
          verbose:                    false
        error:
          handle:                     false
      js:
        lib:
        app:
        export:                       false
        minify:                       false
      dialogs:
        libraries:                    [pgwjs]
        default:
          modal:                      bootstrap
          message:                    toastr
        toastr:
          options:
            closeButton:              true
            positionClass:            toast-top-center
        assets:
          include:
            all:                      true
